# Generated by Django 5.0.7 on 2024-07-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=255)),
                ('rest_spec', models.CharField(max_length=255)),
                ('rest_address', models.CharField(max_length=255)),
                ('rest_website', models.CharField(max_length=255)),
                ('rest_phone', models.IntegerField(max_length=14)),
            ],
        ),
    ]
